# Generated by Django 4.2.2 on 2023-07-25 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(default='<built-in method today of type object at 0x00007FFA0A838570>', max_length=100, verbose_name='тема')),
                ('message_content', models.TextField(blank=True, null=True, verbose_name='содержимое')),
                ('message_created_at', models.DateField(default=datetime.date.today, verbose_name='создан')),
                ('message_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('message_created_at',),
            },
        ),
    ]
