# Generated by Django 4.2.2 on 2023-07-26 16:05

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_created_at',
            field=models.DateField(default=django.db.models.functions.datetime.Now, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_title',
            field=models.CharField(default="<class 'django.db.models.functions.datetime.Now'>", max_length=100, verbose_name='тема'),
        ),
    ]
