# Generated by Django 4.2.2 on 2023-07-26 16:17

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_created_at',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_title',
            field=models.CharField(default='Новое сообщение', max_length=100, verbose_name='тема'),
        ),
    ]
