# Generated by Django 4.2.2 on 2023-07-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_message_message_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-message_created_at',), 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
