# Generated by Django 4.2.2 on 2023-07-26 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='создано'),
        ),
    ]
