# Generated by Django 4.2.2 on 2023-07-22 17:54

from django.db import migrations, models
import django.template.defaulttags


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_name', models.CharField(default='Рассылка 2023-07-22 20:54:10.325411', max_length=255, verbose_name='Рассылка')),
                ('distribution_start', models.DateTimeField(default=django.template.defaulttags.now, verbose_name='Дата начала рассылки')),
                ('distribution_end', models.DateTimeField(default=django.template.defaulttags.now, verbose_name='Дата окончания рассылки')),
                ('distribution_is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('periodicity', models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Раз в день', max_length=25, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Активирована', 'Активирована'), ('Завершена', 'Завершена')], default='Создана', max_length=25, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
