# Generated by Django 4.2.2 on 2023-07-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='distribution_name',
            field=models.CharField(default='Рассылка 2023-07-23 16:22:49.655842', max_length=255, verbose_name='Рассылка'),
        ),
    ]
