# Generated by Django 4.2.2 on 2023-07-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_distribution_distribution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='distribution_name',
            field=models.CharField(default='Рассылка', max_length=255, verbose_name='Рассылка'),
        ),
    ]
