# Generated by Django 4.2.2 on 2023-07-31 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_message_message_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_distribution_distribution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='distribution_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.message', verbose_name='сообщение'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='distribution_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distribution_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distribution_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала рассылки'),
        ),
    ]
