# Generated by Django 4.2.2 on 2023-07-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_distribution_distribution_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='distribution_is_active',
            field=models.BooleanField(default=False, verbose_name='Активная'),
        ),
    ]
