# Generated by Django 4.2.2 on 2023-08-08 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('main', '0008_alter_distribution_distribution_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDCross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_cross_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='клиент')),
                ('cd_cross_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.distribution', verbose_name='рассылка')),
            ],
        ),
    ]
